name: "CI Cachix Matrix Build"

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'flake.lock'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      packages: ${{ steps.changed-pkgs.outputs.packages }}
      flake_changed: ${{ steps.changed-pkgs.outputs.flake_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed packages
        id: changed-pkgs
        run: |
          BASE_SHA="HEAD~1"
          CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD)
          
          # Check if flake.lock was part of the merge/push
          LOCK_CHANGED=$(echo "$CHANGED_FILES" | grep -q '^flake.lock$' && echo "true" || echo "false")
          
          if [ "$LOCK_CHANGED" = "true" ]; then
            echo "flake.lock changed."
          else
            CHANGED=$(echo "$CHANGED_FILES" | grep '^packages/' | awk -F'/' '{print $2}' | sort -u | xargs)
          fi
          
          echo "Detected changed packages: $CHANGED, flake_changed: $LOCK_CHANGED"
          echo "packages=$CHANGED" >> $GITHUB_OUTPUT
          echo "flake_changed=$LOCK_CHANGED" >> $GITHUB_OUTPUT

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.packages != '' || needs.detect-changes.outputs.flake_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: nix-substratum
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run nix-fast-build (Flake Changed)
        if: needs.detect-changes.outputs.flake_changed == 'true'
        run: |
          nix run github:Mic92/nix-fast-build -- \
            -f .#packages.${{ matrix.system }} \
            --skip-cached \
            --no-nom

      - name: Run nix-fast-build (Specific Packages)
        if: needs.detect-changes.outputs.flake_changed != 'true'
        run: |
          ARGS=()
          for pkg in ${{ needs.detect-changes.outputs.packages }}; do
            ARGS+=("-f" "#packages.${{ matrix.system }}.$pkg")
          done
          
          nix run github:Mic92/nix-fast-build -- \
            "${ARGS[@]}" \
            --skip-cached \
            --no-nom
